service:
  name: serverless-101
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpPort: 3000
  

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  tags:
    project: serverless-101
    createdBy: Jose Guillen

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  
  goodbye:
    handler: handler.goodbye
    events:
      - http:
          method: post
          path: goodbye
